controller_manager:
  ros__parameters:
  
    update_rate: 100 
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
 
joint_trajectory_controller:
  ros__parameters:

    joints:
      - base joint
      - slider_joint
      - arm_joint
  
    command_interfaces:
      - position
  
    state_interfaces:
      - position
      - velocity

    # action_monitor_rate: 20.0