<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="macros.xacro"/>

  <link name="world"></link>

  <joint name="base_joint" type="fixed">
    <origin xyz="1.5 1 0"/>
    <parent link="world"/>
    <child link="base_link"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 0.05"/>
      <geometry>
        <box size="2.5 1.5 0.1"/>
      </geometry>
      <material name="green"/>
    </visual>
    <collision>
      <origin xyz="0 0 0.05"/>
      <geometry>
        <box size="2.5 1.5 0.1"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="12" x="2.5" y="1.5" z="0.1">
      <origin xyz="0 0 0.05"/>
    </xacro:inertial_box>
  </link>
  
  <joint name="slider_joint" type="prismatic">
    <origin xyz="-1.25 0 0.1"/>
    <parent link="base_link"/>
    <child link="slider_link"/>
    <axis xyz="1 0 0"/>
    <limit lower="0" upper="2" velocity="100" effort="100"/>
  </joint>

  <link name="slider_link">
    <visual>
      <origin xyz="0 0 0.075"/>
      <geometry>
          <box size="0.5 0.25 0.15"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 0.075"/>
      <geometry>
          <box size="0.5 0.25 0.15"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="0.5" x="0.5" y="0.25" z="0.15">
      <origin xyz="0 0 0.075"/>
    </xacro:inertial_box>
  </link>

  <joint name="arm_joint" type="revolute">
    <origin xyz="0.25 0 0.15"/>
    <parent link="slider_link"/>
    <child link="arm_link"/>
    <axis xyz="0 -1 0"/>
    <limit lower="0" upper="${pi/2}" velocity="100" effort="100"/>
  </joint>

  <xacro:property name="arm_length" value="1"/>
  <xacro:property name="arm_radius" value="0.1"/>
  <link name="arm_link">
    <visual>
      <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>                
          <cylinder length="${arm_length}" radius="${arm_radius}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>                
          <cylinder length="${arm_length}" radius="${arm_radius}"/>
      </geometry>      
    </collision>
    <xacro:inertial_cylinder mass="1.0" length="${arm_length}" radius="${arm_radius}">
      <origin xyz="${arm_length/2} 0 0 " rpy="0 ${pi/2} 0"/>
    </xacro:inertial_cylinder>
  </link>

  <joint name="camera_joint" type="fixed">
        <origin xyz="${arm_length} 0 ${arm_radius + 0.075}"/>
        <parent link="arm_link"/>
        <child link="camera_link"/>        
  </joint>

  <link name="camera_link">
    <visual>
      <origin xyz="-0.03 0 0"/>
      <geometry>
        <box size="0.06 0.15 0.15" />
      </geometry>
      <material name="white"/>
    </visual>
    <visual>
      <origin xyz="0.03 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>
        <cylinder length="0.06" radius="0.04"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0.0 0 0"/>
      <geometry>
        <box size="0.12 0.15 0.15"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="0.1" x="0.12" y="0.15" z="0.15">
      <origin/>
    </xacro:inertial_box>
  </link>

  <xacro:include filename="gazebo.xacro"/>
  <xacro:include filename="control.xacro"/>

</robot>